#pragma once

template <class T>
class CProxy_IImageUploadEvents : public IConnectionPointImpl<T, &__uuidof(_IImageUploadEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
